### ISSUE TITLE
No album type definition found for used print product 'ALB35'

### ISSUE THREAD

**Issue by efji** [albrechtf/mcf2pdf#10]
Hi,

I've tried mcf2pdf and I get this error message:
java.io.IOException: No album type definition found for used print product 'ALB35'
        at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:170)
        at net.sf.mcf2pdf.Main.main(Main.java:181)

It comes from the very first line of my mcf file:
<fotobook createdWithHPSVersion="6000005" totalpages="111" productvariant="pages:106" startdatecalendarium="" designStyle="" productname="ALB35"

BTW, 2 things:
1/ It seems to work very well under MacOS X with the linux version (not suprising).
2/ After install, the directory "Resources" is missing. "mkdir Resources" corrects it but it would be easier if it was been present in the archive.

**Comment by albrechtf** [comment]
Hi efji,

Have you read the installation instructions?

**Comment by efji** [comment]
Le 26/05/2016 à 18:54, Florian Albrecht a écrit :

> Hi efji,
> 
> Have you read the installation instructions?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/albrechtf/mcf2pdf/issues/10#issuecomment-221929976

Hi Florian,

sorry, I had red it but misunderstood the signification of "installation 
directory". Once set to the real photobook directory it runs. But ends 
on this error message (even when I ask for just a few pages) :

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
         at java.awt.image.DataBufferByte.<init>(DataBufferByte.java:92)
         at 
java.awt.image.ComponentSampleModel.createDataBuffer(ComponentSampleModel.java:445)
         at java.awt.image.Raster.createWritableRaster(Raster.java:941)
         at 
javax.imageio.ImageTypeSpecifier.createBufferedImage(ImageTypeSpecifier.java:1074)
         at javax.imageio.ImageReader.getDestination(ImageReader.java:2892)
         at 
com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1071)
         at 
com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1039)
         at javax.imageio.ImageIO.read(ImageIO.java:1448)
         at javax.imageio.ImageIO.read(ImageIO.java:1308)
         at 
net.sf.mcf2pdf.mcfelements.util.ImageUtil.readImage(ImageUtil.java:98)
         at 
net.sf.mcf2pdf.pagebuild.PageImage.renderAsBitmap(PageImage.java:81)
         at 
net.sf.mcf2pdf.pagebuild.BitmapPageBuilder.addToDocumentBuilder(BitmapPageBuilder.java:77)
         at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:211)
         at net.sf.mcf2pdf.Main.main(Main.java:181)

## 

F.J.

**Comment by albrechtf** [comment]
Please check if the instructions at https://github.com/albrechtf/mcf2pdf#troubleshooting can help you.

**Comment by efji** [comment]
Le 26/05/2016 à 21:15, Florian Albrecht a écrit :

> Please check if the instructions at
> https://github.com/albrechtf/mcf2pdf#troubleshooting can help you.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/albrechtf/mcf2pdf/issues/10#issuecomment-221966897

Great! It works (the only remaining problem is the black background of 
the pages that is white now, but it is not very important).

Thanks a lot

## 

F.J.
