### ISSUE TITLE
text quality issues

### ISSUE THREAD

**Issue by lkampsch** [albrechtf/mcf2pdf#11]
Hi there,
thanks for this wonderful project, you really made my day when I found it yesterday!

In general, the conversion went very well. I'm just struggeling with the text boxes:
- the quality of the text is rather pixelated and thus hard to read (I'm using Arial 10pt). Is there a way to include the text as real text (not image) in the pdf? (or am I just too stupid to use the software?)
- the text in the text pdf seems to be slighly larger thus breaking differently in some text boxes und pushing out text of the box.

screenshot cewe:
![image](https://cloud.githubusercontent.com/assets/23510173/20366799/f9147708-ac4c-11e6-98ad-a2fb6669ac32.png)

screenshot pdf:
![image](https://cloud.githubusercontent.com/assets/23510173/20366819/15d3a81e-ac4d-11e6-8f46-08b042c07cf2.png)

Another minor issue that can be seen on the screenshots is the "binding", that is sitting slighly outside the middle. (I used a 20x20 cm square book here)

Thanks for your help and this wonderful project!

**Comment by albrechtf** [comment]
To avoid this "pixelated" effect, please try `-r 300` as output resolution parameter. Currently, everything is rendered as bitmap and then added to the PDF, as this usually produces results better matching the original (although you provided an example where this is not the case).

Rendering as vector information is prepared in the source code of the project, but not yet implemented. Maybe, one day...

Still, both issues are very valid (text wrap and binding position) - I will try to fix it as soon as time permits...
Thanks for the report and the screenshots!

**Comment by lkampsch** [comment]
Many thanks for the immediate answer!

I produced a new pdf with `-r 300` and the text quality is significantly better (and file size went up as expected...). What is interesting is that the text wrap now is ok on this page (but still broken on other pages). Maybe you can make a clue out of that?

![image](https://cloud.githubusercontent.com/assets/23510173/20368764/b6533aae-ac55-11e6-8c80-efae8718aa27.png)

Thanks again!
