### ISSUE TITLE
impossible de trouver ou charger la classe principale net.sf.mcf2pdf.Main

### ISSUE THREAD

**Issue by focusnum** [albrechtf/mcf2pdf#13]
Hello
i'm french so sorry for my so bad english
the script cannot find "net.sf.mcf2pdf.Main"
I'm using Mac OS X and i use this type of command. Do i'm right ?
~ renaud$ /Users/renaud/Downloads/mcf2pdf-0.3.2/mcf2pdf /Users/renaud/Pictures/NY-2016.mcf output.pdf

thank you

**Comment by albrechtf** [comment]
Could you please post the full error output? Thanks!

**Comment by focusnum** [comment]
No problem, but it's in french...
Mini-de-Renaud:~ renaud$ /Users/renaud/Downloads/mcf2pdf-0.3.2/mcf2pdf /Users/renaud/Pictures/NY-2016.mcf output.pdf
Erreur : impossible de trouver ou charger la classe principale net.sf.mcf2pdf.Main
Mini-de-Renaud:~ renaud$

**Comment by albrechtf** [comment]
Hmm, just had a look at the startup script. It seems that you must invoke it in the directory where mcf2pdf is located. I will create a bug ticket for this.

As a workaround, please use this:

```
cd /Users/renaud/Downloads/mcf2pdf-0.3.2
./mcf2pdf /Users/renaud/Pictures/NY-2016.mcf /Users/renaud/Pictures/output.pdf
```

**Comment by albrechtf** [comment]
Bug ticket created as issue #14.

**Comment by focusnum** [comment]
Yes ! it's work.... a bit more :)
i have another problem... sorry...
So i try your command line and i have this

mcf2pdf-0.3.2 renaud$ /Users/renaud/Pictures/NY-2016.mcf /Users/renaud/Pictures/output.pdf
-bash: /Users/renaud/Pictures/NY-2016.mcf: Permission denied

No permission ? strange no ?
Thx for your help

**Comment by focusnum** [comment]
i move .mcf file and photos in the same folder of mcf2pdf and i have this message now...
Mini-de-Renaud:mcf2pdf-0.3.2 renaud$ ./mcf2pdf /Users/renaud/Downloads/mcf2pdf-0.3.2/NY-2016.mcf output.pdf
[ERROR] net.sf.mcf2pdf.Main An exception has occured
java.io.IOException: MCF Resources Directory /Applications/Atelier Photo Fnac.app/Resources does not exist
	at net.sf.mcf2pdf.Mcf2FoConverter.<init>(Mcf2FoConverter.java:94)
	at net.sf.mcf2pdf.Main.main(Main.java:181)

**Comment by focusnum** [comment]
I think, the path is not correct. On my mac i think the correct path is 

/Applications/Atelier\ Photo\ Fnac.app/Contents/Resources  (this is from my Terminal)

**Comment by focusnum** [comment]
is the topic closed ?

**Comment by aschafu** [comment]
As a note for any Mac users: The path you need includes the "Contents" directory (e.g. "/Applications/Meine\ CEWE\ FOTOWELT.app/Contents/").
