### ISSUE TITLE
For big books the cover is cut on the right page

### ISSUE THREAD

**Issue by beaune33** [albrechtf/mcf2pdf#15]
I really like mcf2pdf, its nearly perfect. There is only one thing I don't like. The size of the book cover is always set to a fixed number (420*275). The problem is, if you have books with foto paper and a large number of pages, then the picture used for the printed book has a bigger width than 420. The bigger the book is, the more likely is that someting relevant is cut on the right side of the pdf.

I would appreciate it if the thickness of the book would be taken into account and the cover would be created in the size: 420 + book thickness * 275.

**Comment by gizmo21** [comment]
Same here on a 114page (Fotopapier Matt) / 59 PDF-Pages book it really moves a non-background-coverpicture quite outside of the center.
If you do a temporary workaround by using it as background it cuts away the spine-text
