### ISSUE TITLE
Background (e.g. Color) is not rendered correctly

### ISSUE THREAD

**Issue by berndci** [albrechtf/mcf2pdf#18]
Great program - I'm still looking an the development since version 0.2...
Thank you very much!

One bug is still present (I have tested it today with 0.3.2 and CEWE 6.2):
if a background (e.g. a color) is set, the rendering do not include the background. It is always white.

It would be great, if you would fix this problem.

A hint for all users:
if you have old files, sometimes it is better to load the old file in the CEWE-Editor and make a backup (save as). A lot of problems are gone when you are using the new file with MCF2PDF...

**Comment by boggiz** [comment]
Version Photocité: 6.1.5
Version mcf2pdf: 3.0.2
(Excuse my poor English I'm French and Google Translator)

The conversion of an album of 114 pages is more than correct but there is a bug in the conversion of black background pages. Let me explain:

Here a page descriptor in the original .MCF file:
  <background rotation="0" type="1" alignment="1" templatename="Schwarz,normal,"/>
  
When mcf2pdf meet "Schwarz" (black background) it converts it to "White". (Text in white does not appears).
If a I edit .MCF and change templatename to "6110, Normal" the background is greyed and the text reappears but the background is grey not black.

1) Could you modified your source to correctly printed black background? or tell me how to do that.

At the end of the convert I have this message:
    Warning: Could not get charToByteConverterClass!
2) How to correct that ?

Bests regards

**Comment by albrechtf** [comment]
Please check if this issue is resolved with the 0.3.3 release: https://github.com/albrechtf/mcf2pdf/releases/tag/mcf2pdf-0.3.3 Thanks!

**Comment by berndci** [comment]
Works perfekt !
Great job !
Thanks.
