### ISSUE TITLE
Support for webp

### ISSUE THREAD

**Issue by rbodziony** [albrechtf/mcf2pdf#23]
All images were converted from jpg or PNG to webp

**Comment by albrechtf** [comment]
Hmm, a little more info would really be helpful. What do you mean? Did CEWE change the image format?

**Comment by rbodziony** [comment]
hi yea
all background colours which were before in ..Resources\photofun\backgrounds...
were before .jpg/.png but now all after upgrade are 
.webp
files so imageio can load it as backdround let me pull what i did for background and you will see

**Comment by rbodziony** [comment]
added pull request so you can see if you want some sample files let me know

**Comment by albrechtf** [comment]
Support for WebP has been included in 0.3.3 release, see here for details: https://github.com/albrechtf/mcf2pdf/releases/tag/mcf2pdf-0.3.3
