### ISSUE TITLE
Black background converted to White

### ISSUE THREAD

**Issue by boggiz** [albrechtf/mcf2pdf#27]
Version Photocité: 6.1.5
Version mcf2pdf: 3.0.2
(Excuse my poor English I'm French and Google Translator !!!)

The conversion of an album of 114 pages is more than correct but there is a bug in the conversion of black background pages. Let me explain:

Here a page descriptor in the original .MCF file:
        background rotation="0" type="1" alignment="1" templatename="Schwarz,normal,"/

When mcf2pdf meet "Schwarz" (black background) it converts it to "White". (Text in white does not appears)

If a I edit .MCF and change templatename to "6110, Normal" the background is greyed and the text reappears but the background is grey not black.

Could you modified your source for correctly printed black background? or tell me how to do that.

At the end of the convert I have this message:
Warning: Could not get charToByteConverterClass!
How to correct that ?

Bests regards

**Comment by boggiz** [comment]
OK. I found part of the answer by downloading new colors. Click on:
Backgrounds / More ... / Category / More categories / Colors

The range of Photocité colors is stored in:
C: \ Program Files \ UNIVERS Photocite \ Resources \ photofun \ backgrounds

The color number is simply the name of the file= 212.jpg
Replace all templatename = "Schwarz by templatename =" 212

It's done. Florian your soft is great !!!

**Comment by rbodziony** [comment]
you can try use my fork version with pull request's #19 #26 should work

**Comment by boggiz** [comment]
Thank you for your answer but I'm not Java specialist I will wait for a next update which I hope will incorporate your correction!

**Comment by albrechtf** [comment]
I tried to merge the contributions into latest release 0.3.3, please check if your issue is resolved now: https://github.com/albrechtf/mcf2pdf/releases/tag/mcf2pdf-0.3.3 Thanks!
