### ISSUE TITLE
Fatal error  during processing pagetext coredump

### ISSUE THREAD

**Issue by rbodziony** [albrechtf/mcf2pdf#30]
During processing page area
...
` <area alpha="1" height="387.737" top="1478.5215" zposition="1000" left="98.226" rotation="0" isResizable="1" width="744.4440000000001" areatype="textarea" applySpotColor="0">
   <border position="inside" enabled="0" color="#ff000000" width="5" applySpotColor="1"/>
   <text areaTextType="all" isSpineText="0"><![CDATA[<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd"><html><head><meta name="qrichtext" content="1" /><style type="text/css">p, li { white-space: pre-wrap; }</style></head><body style=" font-family:'CalligraphScript'; font-size:20pt; font-weight:600; font-style:normal;"><table style="-qt-table-type: root; margin-top:5px; margin-bottom:5px; margin-left:5px; margin-right:5px;"><tr><td style="border: none;"><p align="center" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" color:#000000;">Aaaamiaa Baaaaaaw</span></p><p align="center" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" color:#000000;">ccccc bbbbb</span></p></td></tr></table></body></html>]]><outline enabled="0" width="1"/>
    <textFormat foregroundColor="#ff000000" hasOutline="0" VerticalIndentMargin="50" IndentMargin="5" backgroundColor="#00000000" font="CalligraphScript,20,-1,5,75,0,0,0,0,0" Alignment="ALIGNHCENTER"/>
   </text>
  </area>`
crash with error:
... 
[DEBUG] net.sf.mcf2pdf.pagebuild.PageText Rendering text
rest in log hs_err_pid7396.log:
....
[hs_err_pid7396.log](https://github.com/albrechtf/mcf2pdf/files/1463756/hs_err_pid7396.log)

**Comment by albrechtf** [comment]
Could you perhaps please provide a full MCF file for better reproduction? Have you tried another version of Java (e.g. latest update of Java 8)?

**Comment by rbodziony** [comment]
Hi 
 I will try with jdk 8 .
the full mcf i think is not needed because during generation crash is at not first pages but i'm the middle
 Hmm i ll try to create branch with unit test for this issue  ok?

**Comment by rbodziony** [comment]
Using jdk 8 works
