### ISSUE TITLE
Feature request: page numbering

### ISSUE THREAD

**Issue by FridoDeluxe** [albrechtf/mcf2pdf#35]
The Pixum software (respective .mcf files are compatible with the mcf2pdf conversion) provides a feature to enable page numbers on all inner pages. The corresponding part of the .mcf file seems to be this:

```
<pagenumbering format="0" verticalMargin="100" fontbold="0" fontitalics="0" bgcolor="#00000000" position="4" textcolor="#ff000000" margin="150" fontsize="14" fontfamily="Linux Libertine Display O" textstring="%">
  <outline enabled="0" width="1"/>
</pagenumbering>
```

Page numbers would be great. They make life easier when proof reading the converted .pdf file. Thanks!

If you need more information about details of page numbering behaviour and possible values in .mcf files I could try to provide that.

**Comment by DuncanLithgow** [comment]
I think mcf2pdf should stick to being a converter.

**Comment by FridoDeluxe** [comment]
In case my feature request was unclear: I don't want mcf2pdf to generate any page numbers by itself. But photo book software allows to define page numbers and automatically add them to the page layout, they are also printed in the end. All I want is having these page numbers converted, too.

**Comment by DuncanLithgow** [comment]
In that case I have deleted my objection. I misunderstood, thanks for following up.
