### ISSUE TITLE
png and gif

### ISSUE THREAD

**Issue by haraldballuch** [albrechtf/mcf2pdf#4]
This is more a kind of a feature request. When i insert files in png or gif format, i get an error ("File is not the correct format"). if I convert the pictures to jpeg first, the conversion works fine.

**Comment by haraldballuch** [comment]
This is also a problem, if one uses the editor of the cewe software, for example to cut pictures. The editor converts the files to png and after that mcf2pdf fails to convert, because it can't handle png format.

**Comment by albrechtf** [comment]
Support for PNG has just been merged into the code base (thanks to @ebkraus for contribution). Will be included in the next release, so stay tuned ;-)

**Comment by haraldballuch** [comment]
That's good news :)

**Comment by albrechtf** [comment]
Closed as this should be resolved with 0.3.3 release. Feel free to re-open if issue still exists.
