### ISSUE TITLE
UnsatisfiedLinkError: Unable to load library libwebp.dll

### ISSUE THREAD

**Issue by TheKingT** [albrechtf/mcf2pdf#41]
Unable to load library 'libwebp.dll':

Using 
Java 8 (Update 151)
mcf2pdf-mcf2pdf-0.3.4 
CEWE 06.03.01 
under Windows10 with the following input and error message

------------------

> E:\users\thomas\Computer\mcf2pdf-0.3.4>mcf2pdf "E:\users\thomas\Computer\mcf2pdf-0.3.4\Digitales Fotoalbum\Kinder Fotobuch 2017.mcf" Kinder_Fotobuch_2017.mcf.pdf -r 300
> [INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering cover...
> [WARN ] net.sf.mcf2pdf.pagebuild.PageBackground Background not found for page 0: fullcoverpage_portrait
> [WARN ] net.sf.mcf2pdf.pagebuild.PageBackground Background not found for page 0: kino_cover_back_portrait
> [INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering pages 0+1...
> Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'libwebp.dll': Native library (win32-x86/libwebp.dll) not found in resource path ([file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/jdom-1.1.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/fop-1.0.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/xmlgraphics-commons-1.4.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/batik-svg-dom-1.7.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/batik-anim-1.7.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/batik-parser-1.7.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/batik-bridge-1.7.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/batik-script-1.7.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/batik-js-1.7.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/batik-xml-1.7.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/xalan-2.6.0.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/batik-awt-util-1.7.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/batik-gvt-1.7.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/batik-transcoder-1.7.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/batik-extension-1.7.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/batik-ext-1.7.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/commons-io-1.3.1.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/avalon-framework-api-4.3.1.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/avalon-framework-impl-4.3.1.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/batik-svggen-1.7.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/batik-util-1.7.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/xml-apis-1.3.04.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/batik-swing-1.7.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/batik-css-1.7.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/batik-dom-1.7.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/batik-gui-util-1.7.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/xml-apis-ext-1.3.04.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/batik-codec-1.7.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/commons-digester3-3.1.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/commons-logging-1.1.1.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/commons-beanutils-1.8.3.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/commons-cli-1.2.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/log4j-1.2.9.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/jempbox-1.6.0.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/metadata-extractor-2.9.1.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/xmpcore-5.1.2.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/pngj-2.1.0.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/jna-4.1.0.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/jna-platform-4.1.0.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/junit-4.11.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/hamcrest-core-1.3.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/lib/jai-imageio-core-1.3.0.jar, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/%22C:/Program%20Files/CEWE%20FOTOSERVICE/CEWE%20FOTOSERVICE%22, file:/E:/users/thomas/Computer/mcf2pdf-0.3.4/mcf2pdf-0.3.4.jar])
>         at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
>         at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
>         at com.sun.jna.Library$Handler.<init>(Library.java:147)
>         at com.sun.jna.Native.loadLibrary(Native.java:412)
>         at com.sun.jna.Native.loadLibrary(Native.java:391)
>         at net.sf.mcf2pdf.mcfelements.util.webp.Webp.loadLibrary(Webp.java:42)
>         at net.sf.mcf2pdf.mcfelements.util.ImageUtil.internalRead(ImageUtil.java:267)
>         at net.sf.mcf2pdf.mcfelements.util.ImageUtil.readImage(ImageUtil.java:84)
>         at net.sf.mcf2pdf.pagebuild.PageBackground.drawBackground(PageBackground.java:76)
>         at net.sf.mcf2pdf.pagebuild.PageBackground.renderAsBitmap(PageBackground.java:61)
>         at net.sf.mcf2pdf.pagebuild.BitmapPageBuilder.addToDocumentBuilder(BitmapPageBuilder.java:77)
>         at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:240)
>         at net.sf.mcf2pdf.Main.main(Main.java:188)

------------------

Anything I can do about it?

Thanks very much!!!

**Comment by And-Mit** [comment]
Hi
Same issue for me
Java 8 (Update 144)
Win 7 Pro
mcf2pdf-0.3.4
Thanks for your help !

**Comment by boggiz** [comment]
Hi,
This problem is known see issue: https://github.com/albrechtf/mcf2pdf/issues/29
I think it's the same for Windows 10. 
For W10, you have to download the file 64b there:  https://fr.dll-files.com/libwebp.dll.html
and install it in the directory  Windows\System32
I think that will correct your problem.
