### ISSUE TITLE
See warningsbelow. How to solve them during rendering?

### ISSUE THREAD

**Issue by Tom54497** [albrechtf/mcf2pdf#47]
[WARN ] net.sf.mcf2pdf.pagebuild.PageBackground Background not found for page 0: Weiss
Warning: Could not get charToByteConverterClass!

**Comment by albrechtf** [comment]
The second warning is a warning of the PDF converter library which cannot be (easily) suppressed.

The first warning indicates that a file could not be found within the MCF resource locations. As is seems to be a not-that-dramatic change in result (the white background file is not loaded), you can safely ignore it for now.

If you really want to get rid of this message, check your mcf2pdf setup (check the README), and search for a file named "Weiss" in all resource locations of the CEWE software.
