### ISSUE TITLE
Unsupported JPEG process: SOF type 0xcf

### ISSUE THREAD

**Issue by martind1983** [albrechtf/mcf2pdf#48]
First of all thanks for the great program. I could overcome the issues with the missing dll, but now... after ~100 pages of rendering i am getting this error, any ideas? 

[ERROR] net.sf.mcf2pdf.Main An exception has occured
javax.imageio.IIOException: Unsupported JPEG process: SOF type 0xcf
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.readImage(Native Method)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(Unknown Source)
        at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(Unknown Source)
        at javax.imageio.ImageIO.read(Unknown Source)
        at javax.imageio.ImageIO.read(Unknown Source)
        at net.sf.mcf2pdf.mcfelements.util.ImageUtil.internalRead(ImageUtil.java:273)
        at net.sf.mcf2pdf.mcfelements.util.ImageUtil.readImage(ImageUtil.java:84)
        at net.sf.mcf2pdf.pagebuild.PageImage.renderAsBitmap(PageImage.java:101)
        at net.sf.mcf2pdf.pagebuild.BitmapPageBuilder.addToDocumentBuilder(BitmapPageBuilder.java:77)
        at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:240)
        at net.sf.mcf2pdf.Main.main(Main.java:188)

Java 1.8.0_171-b11
Win10
(Built with Pixum, reopened and saved again with Cewe. Tried to convert the cewe file.)

**Comment by rbodziony** [comment]
Did you tried less pages ? <100 ? or orginal from pixum ?

**Comment by martind1983** [comment]
I have 2 books created in pixum, reopened with cewe, checked, and saved with cewe (both looking good in cewe program as well). 
I tried also original pixum file, does not really work to convert.

Trying to convert them, one worked more or less, the 2nd one mentioned here stopps after page 116.  
I tried already to reduced output with -n option to 100 pages. it is working for the first 100 pages.
Any ideas how to overcome this error?

**Comment by rbodziony** [comment]
Hmm you can try isolate error cut all pages on xml and check at which exact page it fails

**Comment by martind1983** [comment]
ok will do so as soon as i find some time ;-) thanks for your help

btw: i also get another Warning: Could not get charToByteConverterClass!

**Comment by martind1983** [comment]
In additon, 2nd book can be created, but following "export issue": 

this is how it looks in the program:
![design_blackbackground](https://user-images.githubusercontent.com/41088233/42733871-f70d5e8c-8839-11e8-9451-67f504bb0bf1.PNG)
this is the generated output: ![output_blackbackground](https://user-images.githubusercontent.com/41088233/42733872-f72dde28-8839-11e8-92f4-7a04f4b5ed01.PNG)
somehow the white and black backgrounds are not correctly recongized by mcf2pdf?

Always following error message:
[WARN ] net.sf.mcf2pdf.pagebuild.PageBackground Background not found for page xx: Schwarz
[WARN ] net.sf.mcf2pdf.pagebuild.PageBackground Background not found for page xx: Weiss

**Comment by rbodziony** [comment]
For this second issue is a pull req for fixing this i will try find some time to create new version with pull requests you can also try apply pull requests

**Comment by martind1983** [comment]
can you provide more details please, how to apply pull requests? what does this mean :) sorry for keeping you busy ;)

**Comment by rbodziony** [comment]
hi
 Can you download https://github.com/rbodziony/mcf2pdf/releases/tag/mcf2pdf-0.3.5
 and check this version ?

**Comment by martind1983** [comment]
0.3.5 working much better. backgrounds are now correct :-)

following issue still with this image which should not be there on the first content page:
![grafik](https://user-images.githubusercontent.com/41088233/42983583-ce391706-8be7-11e8-9594-67c1ea143ad8.png)

btw I get the following warning:
Warning: Could not get charToByteConverterClass!
[INFO ] net.sf.mcf2pdf.mcfelements.util.PdfUtil Generated 51 PDF pages in total.

**Comment by martind1983** [comment]
i tried the other book as well with more pages, this time mcf2pdf stopped immediately after start with following error: 
[INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering cover...
[ERROR] net.sf.mcf2pdf.Main An exception has occured
java.lang.ClassCastException: org.jsoup.nodes.TextNode cannot be cast to org.jsoup.nodes.Element
        at net.sf.mcf2pdf.pagebuild.PageText.parseText(PageText.java:107)
        at net.sf.mcf2pdf.pagebuild.PageText.<init>(PageText.java:59)
        at net.sf.mcf2pdf.Mcf2FoConverter.processDoublePage(Mcf2FoConverter.java:293)
        at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:221)
        at net.sf.mcf2pdf.Main.main(Main.java:202)

**Comment by rbodziony** [comment]
https://github.com/rbodziony/mcf2pdf/issues can you put debug there as new issue ?

**Comment by gizmo21** [comment]
@rbodziony thanks for compiling a new version with those various great fixes of other devs out there since version 0.34. Could you tell me if have added all the branches of https://github.com/cdce8p/mcf2pdf/branches/all especially the "spine" fixes for books with many pages? 

cdce8p is not able to compile a version now, thx for your work.

**Comment by rbodziony** [comment]
Yes this was added

**Comment by martind1983** [comment]
any idea why this image shows up even though it does not show up in the fotobuch itself?

**Comment by rbodziony** [comment]
for issue with "eggs" pls open new issue at rbodziony issues and put from xml some initial part  via gist  https://help.github.com/articles/about-gists/

**Comment by rbodziony** [comment]
also run it with debug mode -d
