### ISSUE TITLE
Special characters appear blank

### ISSUE THREAD

**Issue by andersthomas** [albrechtf/mcf2pdf#49]
First of all, thank you for the great software which already does an amazing job producing output very close to the original product.

I noticed a small glitch (running on Windows 10 with a partner version of CEWE software 6.3.4): when the mcf file contains <text> with special characters (e.g. "č"), then the special characters appears as a blank/space in the PDF output.

Is there a workaround?

**Comment by rbodziony** [comment]
can you check this version https://github.com/rbodziony/mcf2pdf/releases/tag/0.3.6?

**Comment by andersthomas** [comment]
I've tried https://github.com/rbodziony/mcf2pdf/releases/tag/0.3.6, but it shows the same symptoms.

**Comment by rbodziony** [comment]
Tx for info could possibly add debug log here from running?

**Comment by andersthomas** [comment]
Add a single special character (e.g. "č") in the text part of one of your own mcf files would probably be the easiest way to reproduce. Are you saying that it works for you?

**Comment by rbodziony** [comment]
Yes I've got many special char like ó ą etc so I wanted check your mcf file why it didn't work
Regards
