### ISSUE TITLE
HTML parsing issue

### ISSUE THREAD

**Issue by wi-fr** [albrechtf/mcf2pdf#51]
I greatly appreciate your initiative to develop the MCF to PDF converter. 

When text areas in our .mcf files contain several paragraphs, only the first one shows up in the PDF. Here's an example:

<text isSpineText="0" areaTextType="content" applySpotColor="0"><![CDATA[<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd"><html><head><meta name="qrichtext" content="1" /><style type="text/css">p, li { white-space: pre-wrap; }</style></head><body style=" font-family:'Arial'; font-size:12pt; font-weight:400; font-style:normal;"><table style="-qt-table-type: root; margin-top:5px; margin-bottom:5px; margin-left:5px; margin-right:5px;"><tr><td style="border: none;"><p align="justify" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" color:#000000;">Besuch bei den Schlittenhunden im Camp Barentz.</span></p><p align="justify" style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#000000;"><br /></p><p align="justify" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" color:#000000;">Ein einsam gelegenes Haus mit Rentier.</span></p></td></tr></table></body></html>]]><outline color="#ff000000" enabled="0" width="1"/>

In this case "Besuch bei den Schlittenhunden im Camp Barentz." gets rendered whereas "Ein einsam gelegenes Haus mit Rentier." is not. 

I use version 0.3.6

**Comment by rbodziony** [comment]
Hmm can you enable debug and provide output of this page?

**Comment by wi-fr** [comment]
I rendered the the first two pages and uploaded the output and the PDF file. The issue occurs on both of these double-pages. 
   
[mcf2pdf-Debug.txt](https://github.com/albrechtf/mcf2pdf/files/2640728/mcf2pdf-Debug.txt)
[ReykjavikLongyearbyenFotobuch.pdf](https://github.com/albrechtf/mcf2pdf/files/2640729/ReykjavikLongyearbyenFotobuch.pdf)

**Comment by arnkit** [comment]
I Have the same issue - did you find a solution?

**Comment by rbodziony** [comment]
check this version 
https://github.com/rbodziony/mcf2pdf/releases/tag/0.3.7
