### ISSUE TITLE
PDF wont display text in paragraphs

### ISSUE THREAD

**Issue by arnkit** [albrechtf/mcf2pdf#52]
Dear Developers,

Thanks for the great work with mcf2pdf.

I just tried 0.3.6 and it works great accept for text with paragraphs (there was an open issue #51). This has been closed, but the issue seems still to exist. Any suggestions?

Thanks

**Comment by rbodziony** [comment]
Can you close and open issue at my fork?
https://github.com/rbodziony/mcf2pdf

**Comment by arnkit** [comment]
Open an Issue in the fork of rbodziony: https://github.com/rbodziony/mcf2pdf/issues/11
