### ISSUE TITLE
Warning "Could not get charToByteConverterClass!"

### ISSUE THREAD

**Issue by therightdirk** [albrechtf/mcf2pdf#55]
Hi,
thanks for the very good tool (mcf2pdf-0.3.6).
The pdf is generated but I receive the warning "Could not get charToByteConverterClass!"
The text in the boxes is partly cutted off and not adjusted correctly as in the mcf-file I see in CEWE. I changed all text from Verdana to Arial. But that does not help.
Any ideas?
Thanks
Dirk

**Comment by rbodziony** [comment]
hi 
Can you check this version and let me know if it helps ?
https://github.com/rbodziony/mcf2pdf/releases/tag/0.3.7
Grab this version unzip to new folder configure and try generate pdf from this version 
if it dint help paste some part of xml as code here with debug log too :)

**Comment by bmffb** [comment]
Hi,
I have used version 0.3.7 and converted a fotobook containing many text portions. In general, I have used Calibri as font. On many occasions I have observed, that the text is cut off at the end (in the pdf). 
With manipulation of the pixel coordinates and sizes of the text box (in the mcf file) I was able, to get all the original text into the pdf. For me it looks like, that maybe the lineheight in the pdf is a bit too big. I have also observed that for text boxes containing larger font sizes the letters of the text get cut on the top side. The solution for me: I have manipulated (enlarged) the margin-top settings in the text-box html code (in the mcf file). 
It will be probably pretty difficult to incorporate rules into mcf2pdf to cope with these "mcf" bugs.
Regards,
Bernard

**Comment by rbodziony** [comment]
i see can you show some example portion of xmls when you have errors ?

**Comment by therightdirk** [comment]
With 0.3.7 it works perfectly. Thanks, Dirk

**Comment by therightdirk** [comment]
I juast want to add that the appearance of the text in the boxes depends on the choosen Resolution. With r<400> it works.
