### ISSUE TITLE
No display of round pictures (using the edge function)

### ISSUE THREAD

**Issue by bmffb** [albrechtf/mcf2pdf#59]
If I use the edge function in the CEWE fotobook software I can generate a round image, if I choose a squared image and a corner size half of the length of each side. In addition I can use the border function and will end up with a really nice looking round "button"-like image.
Unfortunately, in the PDF only the original squared image shows up. Please find enclosed an example part of the .mcf xml file defining a round image (corners enabled="yes"):
```

<area height="745.9477602273889" left="2762.987769645818" isResizable="1" width="746.2945667709139" alpha="1" rotation="0" areatype="imagearea" top="44" zposition="108">
   <border width="10" applySpotColor="0" position="centered" enabled="1" color="#ffc8663b"/>
   <corners enabled="yes">
    <corner where="bottom-left" shape="convex" length="480"/>
    <corner where="top-right" shape="convex" length="480"/>
    <corner where="bottom-right" shape="convex" length="480"/>
    <corner where="top-left" shape="convex" length="480"/>
   </corners>
   <image safeContainerLocation="persistent" scale="0.248649" left="-748" useABK="0" top="0" filename="2014-Namibia-930.jpeg">
    <relationships>
     <relationship child="2014-Namibia-930.jpeg" nature="RELATIONSHIP_ONE_TO_ONE_COPY" parent="D:/_BILDER/_FOTOBÜCHER/FOTOBUCH_Kathi/2014/2014-Namibia-930.jpg"/>
    </relationships>
   </image>
  </area>
```

It would be great if this could be fixed.

**Comment by rbodziony** [comment]
Which cewe version?

**Comment by bmffb** [comment]
It is version 6.4.1

**Comment by bmffb** [comment]
Working now on the next cewe2pdf conversions I came across the same problem.
I am still using cewe version 6.4.1 and mcf2pdf 3.4. Please find here my workaround for this problem:

The **problem**:
The original foto to use in the fotobook is rectangular. In the cewe software I cut it down to have a square shape. Using the corner function (using some high value, i. e. 1000) results in a circular image. I also use some border decoration. The result is very nice. 
BUT: In the generated pdf all corner settings are not taken into account. It will display the orginal rectangular image (with the border decoration).
Here an example of the respective part of the .mcf file of a circular image:
```
<area zposition="111" width="1040" alpha="1" height="1040" rotation="0" isResizable="1" left="4320" top="39" areatype="imagearea">
	<border applySpotColor="0" enabled="1" width="10" position="centered" color="#ffffffff"/>
	<corners enabled="yes">
	<corner length="520" where="bottom-left" shape="convex"/>
	<corner length="520" where="top-left" shape="convex"/>
	<corner length="520" where="bottom-right" shape="convex"/>
	<corner length="520" where="top-right" shape="convex"/>
	</corners>
	<image filename="image.png" scale="0.93" safeContainerLocation="persistent" useABK="0" left="0" top="-2">
	<relationships>
		<relationship child="image.jpeg" parent="path/image.jpg" nature="RELATIONSHIP_ONE_TO_ONE_COPY"/>
	</relationships>
	</image>
</area>
```

My **workaround** (for each single circular foto):
- I delete the "border" section
- I delete the "corners" section
- I open the original image in some image software (i. e. Photofiltre) and cut out the desired circular part. I will paste this part as new image. If I want some border decoration, I will add this to the new image (the way of doing depends on the software used). 
- The new image is saved as .png (using a transparent background) into the folder containing all the other fotobook images ("fotobook ...._mcf_dateien").
- In the .mcf file the respective image link is changed from ...jpeg to ...png and in the <image  .... left="xxx"> section the value is changed to 0 (usually it is not 0). I do not change the <area   .... left="xxx"> section.
- The result is a perfect circular image in the pdf file.

Enjoy
Bernard
