### ISSUE TITLE
Another Width (0) and height (0) cannot be <= 0 Exception

### ISSUE THREAD

**Issue by wi-fr** [albrechtf/mcf2pdf#62]
I greatly appreciate your inititive. 

Having upgrade the CEWE software to version 6.4.5 (x64), I no longer get beyond the rendering of the cover page on all my photobooks that worked in the past and on newly created ones: 

`[INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering cover...
[ERROR] net.sf.mcf2pdf.Main An exception has occured
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.awt.image.BufferedImage.<init>(Unknown Source)
	at net.sf.mcf2pdf.pagebuild.BitmapPageBuilder.addToDocumentBuilder(BitmapPageBuilder.java:66)
	at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:211)
	at net.sf.mcf2pdf.Main.main(Main.java:188)
`

This exception occurs with both MCF2PDF versions, that I have at hand:  0.3.4 and 0.3.8

**Comment by boggiz** [comment]
I have the same problem see #50

**Comment by chharms** [comment]
For me, now again. Upgraded to CEWE Fotobuch V7.0.1 before.
Similar ERROR as from wi-fr above.

**Comment by thorsten-klein** [comment]
Same Issue for me. 

I installed CEWE Fotobuch 7.0.1 and created my photobook. 
I am not able to convert it with mcf2pdf 0.3.4 --> Same Issue

In a next step I reinstalled CEWE Fotobuch 6.4.1 and tried to open my created photobook. 
Result: The photobook from 7.0.1 cannot be opened.

It seems that CEWE have changed the mcf formatting.
Are you working at this issue so that mcf2pdf supports CEWE 7.0.1?

**Comment by rbodziony** [comment]
Hi
 Im working on next version
Hope to finish it asap .
Regards

**Comment by dl555atp** [comment]
Great idea with the converter. Have same Problem with cewe(DM) 7.0.1 and wait for your next version.
Please add to readme, that TMP-Dir shouldnt (never) end with backslash ;-) Regards

**Comment by Pascal3380** [comment]
Hi 
Not working also for me using file generated using CEWE 6.4.7
But with files generated with CEWE 6.2.6 there is no error.

If I can help you to test it or to do some others task and if I can, thanks to contact me.

Regards
P.

== Error details ===================================
 
 * Error with file generated using CEWE 6.4.7
     Error: Could not find or load main class net.sf.mcf2pdf.Main
     [INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering cover...
     [ERROR] net.sf.mcf2pdf.Main An exception has occured
        java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
        at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
        at java.awt.image.BufferedImage.<init>(Unknown Source)
        at net.sf.mcf2pdf.pagebuild.BitmapPageBuilder.addToDocumentBuilder(BitmapPageBuilder.java:66)
        at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:211)
        at net.sf.mcf2pdf.Main.main(Main.java:188)
Press any key to continue . . .

 * CEWE Version6.4.7 (f0b15c3a)   6/Nov/2019 17:00    788  Win64 Rlease (30/Oc/2019 07:58)
 * Win 10
 * using mcf2pdf version :
        - mcf2pdf-0.3.1
        - mcf2pdf-0.3.4

**Comment by staaash** [comment]
Hi Florian, just a gentle tap on the door: have you managed to make any progress with this issue yet? Anything I/we might be able to help with (e.g. testing)? Is this maybe relevant / helpful: https://www.ibm.com/support/pages/java-exception-javalangillegalargumentexception-width-0-and-height-0-cannot-be ? To quote from that link:

> To resolve the java.lang.IllegalArgumentException exception on Linux, set
> the following environment variable before you run the WebSphere Transformation
> Extender Management Tools:
> 
> export AWT_TOOLKIT=MToolkit
> 
> When you run the WebSphere Transformation Extender Launcher Administration, Management Console, and Resource Registry tools, they
> should now start successfully and not throw the Java exception.

Stay safe! Thanks!!

**Comment by joachim99** [comment]
The problem is that the mcf file format was changed in the newer versions. There is no easy fix.
This exception is just the first of many problems.
