### ISSUE TITLE
ERROR: INFILE and OUTFILE must be specified

### ISSUE THREAD

**Issue by Marl2019** [albrechtf/mcf2pdf#63]
Hi,

I always get the message "INFILE and OUTFILE must be specified. Arguments were: [ ]", but I have specified an infile and outfile (I think). Can someone help me, please? Thank you!

![Unbenannt](https://user-images.githubusercontent.com/55650467/65384562-1311b700-dd24-11e9-8cb8-537ac2c9dc09.JPG)

**Comment by themaramatanga** [comment]
Has anybody found out about this error ? I get the same message. Thanx
