### ISSUE TITLE
no photo frames any more since version 6.1.3 (219067)

### ISSUE THREAD

**Issue by markojerofke** [albrechtf/mcf2pdf#7]
In latest German CEWE version 6.1.3 (219067) (programversion="6001003" in mcf file) the photo frames are not printed any more to pdf. No debug failure messages occur.
Any idea or fix? By the way, fantastic program.

**Comment by staffansahlin** [comment]
I can confirm this issue -- there are no photo frames printed using 6.1.3 CEWE files. Anyway, great program!

**Comment by albrechtf** [comment]
Hm, with my testfiles, everything seems fine even with 6.1.5. Would be great if you could provide a sample MCF file and a screenshot from the software what you would expect it to look like. Thanks!

**Comment by markojerofke** [comment]
Please find attached the mcf file as well as two screenshots of page 4 of the photobook.
The mcf file is just with the dummy extension ".mcf.pdf" as just .mcf cannot be stored.

![cewe](https://cloud.githubusercontent.com/assets/17836131/20039793/8e3292b2-a44a-11e6-81ec-02b497b56e74.png)
![mcf2pdfergebnis](https://cloud.githubusercontent.com/assets/17836131/20039795/9218bc9e-a44a-11e6-8576-540f3e998e01.png)
[DieJerofkes-2011.mcf.pdf](https://github.com/albrechtf/mcf2pdf/files/573958/DieJerofkes-2011.mcf.pdf)

**Comment by markojerofke** [comment]
Closing was my mistake, sorry.

**Comment by albrechtf** [comment]
OK, now I got it. I was always thinking about the "masks" (the shaped borders you can put on pictures). In my test file, there was no picture with such a "plain" border which is why I missed that change in the new file format. Now, everything should be fine. Will release 0.3.2 in a moment.
