### ISSUE TITLE
java.io.IOException: No album type definition found for used print product 

### ISSUE THREAD

**Issue by tabgab** [albrechtf/mcf2pdf#8]
Hi,

I tried to convert an MCF of mine, it would be a big help, but I get this error:

mcf2pdf myfile.mcf output.pdf
[ERROR] net.sf.mcf2pdf.Main An exception has occured
java.io.IOException: No album type definition found for used print product 'ALB1
3'
        at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:179)
        at net.sf.mcf2pdf.Main.main(Main.java:181)

I suspect, that there is an album definition that your software is not able to recognize. Any ideas how I could work around this? 

Thanks,

Gábor

**Comment by rolfangel** [comment]
Have now the Same Problem.
Is there a Solution available?

**Comment by rolfangel** [comment]
Sorry, it differ: no Album ...... for used print product 'ALB62'
Other are same
